param(
    [switch]$js
)

$ErrorActionPreference = "Stop"

$appMain = "source/main.py"
$logoFile = "logo.png"
$appName = "StratigraphicThicknessCalculator"
$generatedBackend = Join-Path $PSScriptRoot "source/generated_desktop_backend.py"

if (-not (Test-Path $appMain)) {
    throw "Error: $appMain not found. Run this script from project root."
}

if (-not (Test-Path $logoFile)) {
    throw "Error: $logoFile not found. Put logo.png in project root."
}

$backendBool = $(if ($js) { 'False' } else { 'True' })
$content = "# Generated by build_executable.ps1. Do not commit (see .gitignore).`nBACKEND_MPL = $backendBool`n"
Set-Content -Path $generatedBackend -Value $content -Encoding utf8

if ($js) {
    Write-Host "Schematic backend: Qt WebEngine + embedded JS (-js); larger bundle."
} else {
    Write-Host "Schematic backend: Matplotlib (default); Qt WebEngine not bundled."
}

if (Get-Command conda -ErrorAction SilentlyContinue) {
    $activeEnv = $env:CONDA_DEFAULT_ENV
    if ($activeEnv -and $activeEnv -ne "geo_stc") {
        Write-Warning "Active conda environment is '$activeEnv' (not geo_stc). Proceeding anyway."
    } elseif (-not $activeEnv) {
        Write-Warning "No active conda environment detected. Proceeding with current Python environment."
    } else {
        Write-Host "Using conda environment: geo_stc"
    }
} else {
    Write-Warning "conda command not found. Proceeding with current Python environment."
}

Write-Host "Executable name: $appName"
Write-Host "Bundling assets: $logoFile, mobile/geometry_embed.html, mobile/geometry-schematic.js"

python -m pip install -r requirements.txt
if ($LASTEXITCODE -ne 0) {
    throw "Dependency installation failed."
}

$extraArgs = @(
    '--hidden-import', 'source.generated_desktop_backend',
    '--hidden-import', 'matplotlib.backends.backend_qtagg',
    '--hidden-import', 'source.mpl_geometry_schematic',
    '--hidden-import', 'source.mpl_schematic_scene'
)

if ($js) {
    $extraArgs += @(
        '--hidden-import', 'PySide6.QtWebEngineWidgets',
        '--hidden-import', 'PySide6.QtWebEngineCore'
    )
} else {
    $extraArgs += @(
        '--exclude-module', 'PySide6.QtWebEngineWidgets',
        '--exclude-module', 'PySide6.QtWebEngineCore',
        '--exclude-module', 'PySide6.QtWebEngineQuick'
    )
}

python -m PyInstaller `
    --noconfirm `
    --onefile `
    --windowed `
    --icon "$logoFile" `
    --add-data "$logoFile;." `
    --add-data "mobile/geometry_embed.html;mobile" `
    --add-data "mobile/geometry-schematic.js;mobile" `
    @extraArgs `
    --name "$appName" `
    "$appMain"

if ($LASTEXITCODE -ne 0) {
    throw "PyInstaller build failed."
}

$distExe = "dist/$appName.exe"
$rootExe = "./$appName.exe"
if (-not (Test-Path $distExe)) {
    throw "Expected built executable not found at $distExe."
}
Copy-Item -Path $distExe -Destination $rootExe -Force

Write-Host ""
Write-Host "Build complete."
Write-Host "Output copied to: $rootExe"
Write-Host "Original remains in: $distExe"
