// Auto-generated from source/batch_schema.py — do not edit by hand.
// Regenerate: python scripts/generate_batch_schema_js.py

const BATCH_SCHEMA = {
  "headers": [
    "well_id",
    "T",
    "M",
    "sigma_M",
    "delta_deg",
    "sigma_delta_deg",
    "phib_deg",
    "sigma_phib_deg",
    "beta1_deg",
    "sigma_beta1_deg",
    "phid1_deg",
    "sigma_phid1_deg",
    "beta2_deg",
    "sigma_beta2_deg",
    "phid2_deg",
    "sigma_phid2_deg"
  ],
  "inputSigmaPairs": [
    {
      "value": "M",
      "sigma": "sigma_M"
    },
    {
      "value": "delta_deg",
      "sigma": "sigma_delta_deg"
    },
    {
      "value": "phib_deg",
      "sigma": "sigma_phib_deg"
    },
    {
      "value": "beta1_deg",
      "sigma": "sigma_beta1_deg"
    },
    {
      "value": "phid1_deg",
      "sigma": "sigma_phid1_deg"
    },
    {
      "value": "beta2_deg",
      "sigma": "sigma_beta2_deg"
    },
    {
      "value": "phid2_deg",
      "sigma": "sigma_phid2_deg"
    }
  ],
  "modelIdByT": {
    "1": "t1",
    "2": "t2",
    "3": "t3",
    "4": "t4",
    "5": "t5",
    "6": "t6",
    "7": "t7",
    "8": "t8"
  },
  "t1Required": [
    "M",
    "delta_deg",
    "phib_deg",
    "beta1_deg",
    "phid1_deg"
  ],
  "t1Unused": [
    "beta2_deg",
    "phid2_deg"
  ],
  "twoBedRequired": [
    "M",
    "delta_deg",
    "phib_deg",
    "beta1_deg",
    "phid1_deg",
    "beta2_deg",
    "phid2_deg"
  ],
  "wrapAzimuthFields": [
    "dip_azimuth1_deg",
    "dip_azimuth2_deg",
    "dip_azimuth_deg",
    "wellbore_azimuth_deg"
  ],
  "defaultValues": {
    "M": 100.0,
    "delta_deg": 20.0,
    "phib_deg": 120.0,
    "beta1_deg": 15.0,
    "phid1_deg": 140.0,
    "beta2_deg": 18.0,
    "phid2_deg": 150.0
  },
  "defaultSigmas": {
    "sigma_M": 0.0,
    "sigma_delta_deg": 0.0,
    "sigma_phib_deg": 0.0,
    "sigma_beta1_deg": 0.0,
    "sigma_phid1_deg": 0.0,
    "sigma_beta2_deg": 0.0,
    "sigma_phid2_deg": 0.0
  },
  "mcSampleCountWeb": 2500,
  "exampleRows": [
    {
      "well_id": "EX-DET-T1",
      "T": 1,
      "M": 100.0,
      "sigma_M": 0.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": "",
      "sigma_beta2_deg": 0.0,
      "phid2_deg": "",
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-DET-T2",
      "T": 2,
      "M": 100.0,
      "sigma_M": 0.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-DET-T3",
      "T": 3,
      "M": 100.0,
      "sigma_M": 0.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-DET-T4",
      "T": 4,
      "M": 100.0,
      "sigma_M": 0.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-DET-T5",
      "T": 5,
      "M": 100.0,
      "sigma_M": 0.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-DET-T6",
      "T": 6,
      "M": 100.0,
      "sigma_M": 0.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-DET-T7",
      "T": 7,
      "M": 100.0,
      "sigma_M": 0.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-DET-T8",
      "T": 8,
      "M": 100.0,
      "sigma_M": 0.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-MC-T1",
      "T": 1,
      "M": 100.0,
      "sigma_M": 1.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": "",
      "sigma_beta2_deg": 0.0,
      "phid2_deg": "",
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-MC-T2",
      "T": 2,
      "M": 100.0,
      "sigma_M": 1.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-MC-T3",
      "T": 3,
      "M": 100.0,
      "sigma_M": 1.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-MC-T4",
      "T": 4,
      "M": 100.0,
      "sigma_M": 1.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-MC-T5",
      "T": 5,
      "M": 100.0,
      "sigma_M": 1.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-MC-T6",
      "T": 6,
      "M": 100.0,
      "sigma_M": 1.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-MC-T7",
      "T": 7,
      "M": 100.0,
      "sigma_M": 1.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    },
    {
      "well_id": "EX-MC-T8",
      "T": 8,
      "M": 100.0,
      "sigma_M": 1.0,
      "delta_deg": 20.0,
      "sigma_delta_deg": 0.0,
      "phib_deg": 120.0,
      "sigma_phib_deg": 0.0,
      "beta1_deg": 15.0,
      "sigma_beta1_deg": 0.0,
      "phid1_deg": 140.0,
      "sigma_phid1_deg": 0.0,
      "beta2_deg": 18.0,
      "sigma_beta2_deg": 0.0,
      "phid2_deg": 150.0,
      "sigma_phid2_deg": 0.0
    }
  ]
};
